spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pim-core-java
    username: root
    password: cencosud
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  application:
    name: pim-core-service
  jackson:
    date-format: yyyy-MM-dd'T'hh:mm:ss
    serialization:
      write-dates-as-timestamps: false
  mvc:
    converters:
      preferred-json-mapper: jackson

